### ISSUE TITLE
Have a different primary_key name on a struct instead of id when using diesel-rs

### ISSUE THREAD

**Issue by adrianbrink** [adrianbrink/lol_store#1]
Follow this to have a struct field with a custom name as the primary key when using diesel-rs.

> Adrian Brink @adrianbrink 22:01
> @sgrif really how?
> does it do the matching via types?
> 
> Sean Griffin @sgrif 22:04
> infer_schema! looks up the primary key name. The Table trait has a type called PrimaryKey and a method called primary_key to access the column. We get the primary key on the struct through the Identifiable trait which abstracts away the name of the field
> 
> Adrian Brink @adrianbrink 22:04
> so, would I have to implement the Identifiable trait myself?
> 
> Sean Griffin @sgrif 22:05
> #[derive(Identifiable)] still assumes id IIRC. I want to add the ability to do something like #[primary_key="foo"] on the struct or #[primary_key] on the field, but I haven't gotten around to it yet
> Yeah you'd just implement it yourself. It's a really easy trait to implement
> 
> Daniel Durante @durango 22:05
> @sgrif happy new year! thanks for taking a look at diesel-rs/diesel#546 wouldn't I need &'a mut for the source attribute though? Or no? 
> 
> Sean Griffin @sgrif 22:05
> impl<'a> Identifiable for &'a User { type Id = &'a i32; fn id(self) -> Self::Id { &self.id } }

**Comment by sgrif** [comment]
For posterity if anybody ends up finding this from their search engine --

This got fixed a long time ago in Diesel. You can annotate your struct with `#[primary_key(foo, bar)]`. See [the docs for `Identifiable`](http://docs.diesel.rs/diesel/associations/trait.Identifiable.html) for details
